spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/doghotel
    username: root
    password: green502

    # 도커 계정
    #url: jdbc:mariadb://192.168.0.144:3306/db_even_last_2
    #username: even_last_2
    #password: cache

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html
